### ISSUE TITLE
Chalchiu trainer not working on Steam Deck

### ISSUE THREAD

**Issue by Monster-Collector** [Curve/chalchiu#1]
Hi,

I’ve followed the install instructions to a T and still can’t get the install dialogue to appear, access the trainer, anything. Is this maybe a Linux limitation? Otherwise I am probably just stupid and installed it wrong lol. I copied the iphlpapi.dll and the Coromon.Mods.zip to the install folder on my SD card (primary/steamapps/common/Coromon) and unzipped it there. All seems to be present and correct but no dice on the mod appearing to activate. Is there a button I need to bind to make the trainer open? Just spitballing of course! Would love to see modding this good function on the Steam Deck.

Thanks 😊

**Comment by Curve** [comment]
You need to specify this under the launch options:

`WINEDLLOVERRIDES="iphlpapi=n,b"`

**Comment by Monster-Collector** [comment]
Thank you so much friend, I’ll try that as soon as I get home from work! 😊 I appreciate you


On 9 Oct 2023, at 6:38 am, Noah ***@***.***> wrote:

﻿

You need to specify this under the launch options:

WINEDLLOVERRIDES="iphlpapi=n,b"

**Comment by Monster-Collector** [comment]
I’ve entered that exact phrase and sadly no dice 😣 Is there something I need to install onto my Deck to get it going? Thank you so much for your help!

**Comment by Rakidas** [comment]
![Uploading IMG_0704.jpeg…]()

**Comment by Monster-Collector** [comment]
![IMG_0704](https://github.com/Curve/chalchiu/assets/57020864/ae36d53f-6be0-4bae-9a42-209b20eb7f96)

**Comment by Curve** [comment]
What does your game directory look like?

Using the same setup it works for me on arch ^^

**Comment by Curve** [comment]
Oh sorry, I think it should be 

`WINEDLLOVERRIDES="iphlpapi=n,b" %command%`

**Comment by Monster-Collector** [comment]
Curve you absolute gent it’s working!!! Thank you so much 😊

**Comment by Curve** [comment]
> Curve you absolute gent it’s working!!! Thank you so much 😊 

Nice to hear, have fun ^^!

**Comment by Noided6669** [comment]
Unfortunately not working for me unless there's an error somewhere in my install. Mod menu is blank in-game. Glad you are planning to update this Curve!

![PXL_20240511_031842645](https://github.com/Curve/chalchiu/assets/169511103/37065f5e-4820-4342-813d-a4ad1083fc25)
![PXL_20240511_031851253](https://github.com/Curve/chalchiu/assets/169511103/7549a42e-c85a-4ae9-b4c8-c058cdaa0cdf)
![PXL_20240511_035427638](https://github.com/Curve/chalchiu/assets/169511103/43ce9856-6661-4a39-91de-23d0d04a213a)

**Comment by Curve** [comment]
What's in the log?

**Comment by Noided6669** [comment]
> What's in the log?

Don't know what I'm looking for but here's some of the log
If there's something specific I should look for  let me know 
![PXL_20240511_194003231](https://github.com/Curve/chalchiu/assets/169511103/67d65d1c-6439-4245-8136-9f909d326fd1)

**Comment by Curve** [comment]
Ohh sorry for not reading the message properly before! 

> Mod menu is blank in-game

This means the loader loads properly but the mod is likely outdated due to a coromon update... Will update soon :D

**Comment by Noided6669** [comment]
> Ohh sorry for not reading the message properly before!
> 
> > Mod menu is blank in-game
> 
> This means the loader loads properly but the mod is likely outdated due to a coromon update... Will update soon :D

No problem thank you Curve!!
